<%@ Page Title="Invoices" Language="C#" MasterPageFile="~/Child.master" AutoEventWireup="true" CodeFile="Invoices.aspx.cs" Inherits="Invoices" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ChildContent1" runat="Server">
        <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <script type="text/javascript">
        function openModal() {
            $('#invoiceModal').modal('show');
        }
    </script>
    <div class="row">
      <div class="col-lg-12">
            <h2 class="page-header"><i class="fa fa-dollar icons"></i>Invoices</h2>
        </div>
    </div>
    <div class="row">
        
        <div class="col-lg-1" style="width: 40px;"><hr /></div>
        <asp:Button ID="btnInvoice" formnovalidate="formnovalidate" OnClientClick="return false" runat="server" Text="New Invoice" CssClass="btn btn-primary" data-toggle="modal" data-target="#invoiceModal" Visible="true" OnClick="btnInvoice_Click"></asp:Button>

        <div class="col-lg-5">
            <asp:GridView ID="InvoiceGridView" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" OnRowDeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="InvoiceDataSource" DataKeyNames="InvoiceID">
                <Columns>
                    <asp:BoundField DataField="InvoiceID" HeaderText="Invoice Code" SortExpression="InvoiceID" ReadOnly="True" />

                    <asp:BoundField DataField="InvoiceAmount" HeaderText="Total Cost" SortExpression="InvoiceAmount"/>

                    <asp:CheckBoxField DataField="CancelledYN" HeaderText="Paid In Full?" SortExpression="CancelledYN" />

                </Columns>
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <!-- SelectCommand="SELECT [InvoiceID] as 'Invoice Code', [InvoiceAmount] as 'Total Cost', [CancelledYN] as 'Paid In Full?' FROM [Invoice]" -->

            <asp:SqlDataSource ID="InvoiceDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:Project %>"  ProviderName="System.Data.SqlClient" SelectCommand="SELECT [InvoiceID], [InvoiceAmount], [CancelledYN] FROM [Invoice]" UpdateCommand="UPDATE [INVOICE] SET [InvoiceAmount] = @InvoiceAmount, [CancelledYN] = @CancelledYN WHERE [InvoiceID] = @InvoiceID">
                <DeleteParameters>
                    <asp:Parameter Name="InvoiceID" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="InvoiceID" />
                    <asp:Parameter Name="InvoiceAmount" />
                    <asp:Parameter Name="CancelledYN" />
                </UpdateParameters>
            </asp:SqlDataSource>

        </div>
    </div>

        <!-- Modal for Invoices -->
    <div class="modal fade" id="invoiceModal" tabindex="-1" role="dialog" aria-labelledby="animalModalLabel" aria-hidden="true">

        <script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
        <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js'></script>
        <%--<link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css'
        media="screen" />--%>

        <div class="modal-dialog modal-dialog-centered" style="max-width: 400px;" role="document">
            <div class="modal-content">
                <%--<asp:UpdatePanel ID="upModal" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
                    <ContentTemplate>--%>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h5 class="modal-title" id="invoiceModalLabel">Add an Invoice</h5>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="form-control-label">Invoice Type</label>
                        <asp:DropDownList ID="ddlInvoiceType" AutoPostBack="true" runat="server" class="form-control" required="required" OnSelectedIndexChanged="ddlInvoiceType_SelectedIndexChanged">
                            <asp:ListItem></asp:ListItem>
                            <asp:ListItem>On-Site</asp:ListItem>
                            <asp:ListItem>Off-Site</asp:ListItem>
                        </asp:DropDownList>

                    </div>
                    <div class="form-group">
                        <label class="form-control-label" id="lblInvoiceCode" runat="server" visible="false">Invoice Code</label>
                        <asp:TextBox ID="txtInvoiceCode" runat="server" class="form-control" required="required" Visible="false"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" id="lblTotalPeople" runat="server" visible="false">Number of People</label>
                        <asp:TextBox ID="txtTotalPeople" value="0" runat="server" class="form-control" required="required" Visible="false" AutoPostBack="true" OnTextChanged="txtTextChanged"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" id="lblPricePerPerson" runat="server" visible="false">Price per Person</label>
                        <asp:TextBox ID="txtPricePerPerson" value="5.00" type="double" runat="server" class="form-control" required="required" Visible="false" AutoPostBack="true" OnTextChanged="txtTextChanged"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" id="lblOffsiteQuantity" runat="server" visible="false">Off-Site Program Quantity</label>
                        <asp:TextBox ID="txtOffsiteQuantity" value="0" runat="server" class="form-control" required="required" Visible="false" AutoPostBack="true" OnTextChanged="txtTextChanged"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" id="lblOffsitePrice" runat="server" visible="false">Price per Off-Site Program</label>
                        <asp:TextBox ID="txtOffsitePrice" value="256.00" type="double" runat="server" class="form-control" required="required" Visible="false" AutoPostBack="true" OnTextChanged="txtTextChanged"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" id="lblAdditionalQuantity" runat="server" visible="false">Additional Program Quantity</label>
                        <asp:TextBox ID="txtAdditionalQuantity" value="0" runat="server" class="form-control" required="required" Visible="false" AutoPostBack="true" OnTextChanged="txtTextChanged"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" id="lblAdditionalPrice" runat="server" visible="false">Price per Additional Program</label>
                        <asp:TextBox ID="txtAdditionalPrice" value="160.00" type="double" runat="server" class="form-control" required="required" Visible="false" AutoPostBack="true" OnTextChanged="txtTextChanged"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" id="lblTravelMiles" runat="server" visible="false">Travel Miles</label>
                        <asp:TextBox ID="txtTravelMiles" value="0" runat="server" class="form-control" required="required" Visible="false" AutoPostBack="true" OnTextChanged="txtTextChanged"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" id="lblMilePrice" runat="server" visible="false">Price per Mile</label>
                        <asp:TextBox ID="txtMilePrice" value="0.57" type="double" runat="server" class="form-control" required="required" Visible="false" AutoPostBack="true" OnTextChanged="txtTextChanged"></asp:TextBox>
                    </div>


                    <div class="form-group">
                        <label class="form-control-label" runat="server" id="lblTotalCost" visible="false">Total Cost</label>
                        <asp:TextBox ID="txtTotalCost" type="double" ReadOnly="true" BackColor="LightGray" runat="server" class="form-control" required="required" Visible="false"></asp:TextBox>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" runat="server" id="lblInvoicePayment" visible="false">Has Payment Been Recieved?</label>
                        <asp:DropDownList ID="ddlInvoicePayment" runat="server" required="required" class="form-control" Visible="false">
                            <asp:ListItem></asp:ListItem>
                            <asp:ListItem>Yes</asp:ListItem>
                            <asp:ListItem>No</asp:ListItem>
                        </asp:DropDownList>
                    </div>

                    <div id="btn">
                        <asp:Button ID="btnSaveInvoice" runat="server" CssClass="btn btn-success btn-group-justified" Text="Save Invoice" OnClick="btnSaveInvoice_Click" /><br />
                    </div>
                    <div id="btn2">
                        <asp:Button Visible="false" ID="btnClearAll" runat="server" CssClass="btn btn-group-justified btn-danger" CausesValidation="false" Text="Clear Fields" formnovalidate="formnovalidate" OnClick="btnClearAllModal_Click" />
                    </div>


                </div>
                <%-- </ContentTemplate>
                    </asp:UpdatePanel>--%>
            </div>
        </div>
   
    
   
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ChildContent2" runat="Server">
</asp:Content>

