<%@ Page Title="Invoices" Language="C#" MasterPageFile="~/Child.master" AutoEventWireup="true" CodeFile="Invoices.aspx.cs" Inherits="Invoices" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ChildContent1" runat="Server">
    <div class="row">
      <div class="col-lg-12">
            <h2 class="page-header"><i class="fa fa-dollar icons"></i>Invoices</h2>
        </div>
    </div>
    <div class="row">
        
        <div class="col-lg-1" style="width: 40px;"><hr /></div>
        <div class="col-lg-5">
            <asp:GridView ID="InvoiceGridView" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" OnRowDeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="InvoiceDataSource">
                <Columns>
                    <asp:BoundField DataField="InvoiceAmount" HeaderText="InvoiceAmount" SortExpression="InvoiceAmount" />

                    <asp:CheckBoxField DataField="CancelledYN" HeaderText="CancelledYN" SortExpression="CancelledYN" />

                    <asp:BoundField DataField="PaymentTotal" HeaderText="PaymentTotal" SortExpression="PaymentTotal"/>

                </Columns>
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            
            <asp:SqlDataSource ID="InvoiceDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:Project %>" SelectCommand="SELECT [InvoiceAmount], [CancelledYN], [PaymentTotal] FROM [Invoice]" ProviderName="System.Data.SqlClient">
            </asp:SqlDataSource>

        </div>
    </div>
   
    
   
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ChildContent2" runat="Server">
</asp:Content>

