<%@ Page Title="Invoices" Language="C#" MasterPageFile="~/Child.master" AutoEventWireup="true" CodeFile="Invoices.aspx.cs" Inherits="Invoices" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ChildContent1" runat="Server">
    <div class="row">
      <div class="col-lg-12">
            <h2 class="page-header"><i class="fa fa-dollar icons"></i>Invoices</h2>
        </div>
    </div>
    <div class="row">
        
        <div class="col-lg-1" style="width: 40px;"><hr /></div>
        <div class="col-lg-5">
            <asp:GridView ID="InvoiceGridView" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" OnRowDeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="InvoiceDataSource" DataKeyNames="InvoiceID">
                <Columns>
                    <asp:BoundField DataField="InvoiceID" HeaderText="Invoice Code" SortExpression="InvoiceID" ReadOnly="True" />

                    <asp:BoundField DataField="InvoiceAmount" HeaderText="Total Cost" SortExpression="InvoiceAmount"/>

                    <asp:CheckBoxField DataField="CancelledYN" HeaderText="Paid In Full?" SortExpression="CancelledYN" />

                </Columns>
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <!-- SelectCommand="SELECT [InvoiceID] as 'Invoice Code', [InvoiceAmount] as 'Total Cost', [CancelledYN] as 'Paid In Full?' FROM [Invoice]" -->

            <asp:SqlDataSource ID="InvoiceDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:Project %>"  ProviderName="System.Data.SqlClient" SelectCommand="SELECT [InvoiceID], [InvoiceAmount], [CancelledYN] FROM [Invoice]" UpdateCommand="UPDATE [INVOICE] SET [InvoiceAmount] = @InvoiceAmount, [CancelledYN] = @CancelledYN WHERE [InvoiceID] = @InvoiceID">
                <DeleteParameters>
                    <asp:Parameter Name="InvoiceID" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="InvoiceID" />
                    <asp:Parameter Name="InvoiceAmount" />
                    <asp:Parameter Name="CancelledYN" />
                </UpdateParameters>
            </asp:SqlDataSource>

        </div>
    </div>
   
    
   
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ChildContent2" runat="Server">
</asp:Content>

