<%@ Page Language="C#" Title="View Users" AutoEventWireup="true" CodeFile="ViewUser.aspx.cs" Inherits="ViewUser" MasterPageFile="~/Child.master" %>

<script runat="server">

</script>

<asp:Content ID="Content1" ContentPlaceHolderID="ChildContent1" Runat="Server">

   <div class="row">
       <div class="col-lg-12">
            <h2 class="page-header"><i class="fa fa-user icons"></i>View Users</h2>
        </div>
    </div>
    <div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="UserID" DataSourceID="SqlDataSource_ViewUser" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" ItemStyle-Width="40%"/>
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
    
    <asp:SqlDataSource ID="SqlDataSource_ViewUser" runat="server" ConnectionString="<%$ ConnectionStrings:Project %>" SelectCommand="SELECT [UserID], [Username] FROM [Users] ORDER BY [UserID]" deleteCommand="delete from users where UserID = @UserID" updatecommand="update users set username = @username where UserID = @UserID">
                <DeleteParameters>
                    <asp:Parameter Name="UserID" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="UserName" />
                </UpdateParameters>
    </asp:SqlDataSource>
    
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ChildContent2" Runat="Server">
</asp:Content>

